using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DormitoryManagementSystem.Infrastructure.Migrations;

public partial class PostgresIdentityColumns : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("ALTER TABLE \"departments\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"buildings\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"rooms\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"guardians\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"announcements\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"expenses\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"DiningMenus\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"maintenance_requests\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"refresh_tokens\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"payments\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("ALTER TABLE \"payments\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"refresh_tokens\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"maintenance_requests\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"DiningMenus\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"expenses\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"announcements\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"guardians\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"rooms\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"buildings\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        migrationBuilder.Sql("ALTER TABLE \"departments\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
    }
}
